# Site settings
title: Body Worn Cameras
email: dave@esq.io
description: > # this means to ignore newlines until "baseurl:"
  A state-by-state analysis of body-worn camera laws.

baseurl: "/bwc" # the subpath of your site, e.g. /blog/
url: "http://dcogc.org" # the base hostname & protocol for your site
twitter_username: DCOGC
github_username:  dcogc

collections:
  files:
    output: true
    permalink: /jurisdictions/:path/

data_source: data

# Build settings
markdown: kramdown
